# Generated by Django 2.2.7 on 2020-02-07 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageDetection', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='remark',
            field=models.CharField(default='temp', max_length=20),
        ),
    ]
