# Generated by Django 3.0.3 on 2020-03-11 18:44

import accounts.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('phone', models.CharField(max_length=20)),
                ('city', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('height', models.SmallIntegerField(default=40, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(10)])),
                ('weight', models.SmallIntegerField(default=40, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(10)])),
                ('smoking', models.BooleanField(default=False)),
                ('profile_picture', models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
