# Generated by Django 2.2.7 on 2020-01-15 13:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20191129_2351'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='age',
            new_name='dateOfBirth',
        ),
        migrations.AlterField(
            model_name='profile',
            name='height',
            field=models.SmallIntegerField(default=40, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='weight',
            field=models.SmallIntegerField(default=40, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(10)]),
        ),
    ]
