# Generated by Django 3.0.3 on 2020-02-27 22:18

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20200116_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePicture',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_path),
        ),
    ]
