# Generated by Django 3.0.3 on 2020-02-28 02:05

import accounts.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_profilepicture'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='accounts.Profile')),
                ('profilePicture', models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profilePicture',
        ),
    ]
