# Generated by Django 3.0.3 on 2020-02-28 02:38

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20200228_0405'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profilePicture',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_path),
        ),
        migrations.DeleteModel(
            name='ProfilePicture',
        ),
    ]
