# Generated by Django 3.0.3 on 2020-02-28 13:11

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20200228_0438'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfilePicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profilePicture', models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name='profile',
            name='profilePicture',
        ),
    ]
