# Generated by Django 3.0.3 on 2020-02-28 13:19

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20200228_1511'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_path),
        ),
    ]
