# Generated by Django 3.0.3 on 2020-02-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_delete_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to='profilePictures'),
        ),
    ]
