# Generated by Django 3.0.3 on 2020-03-09 19:59

import accounts.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20200229_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, max_length=255, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/profile_photos'), upload_to=accounts.models.upload_path),
        ),
    ]
