# Generated by Django 3.0.3 on 2020-03-09 20:10

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_auto_20200309_2159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=accounts.models.upload_path),
        ),
    ]
