# Generated by Django 2.2.7 on 2019-11-06 21:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('weight', models.SmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(10)])),
                ('height', models.SmallIntegerField(default=10, validators=[django.core.validators.MaxValueValidator(300), django.core.validators.MinValueValidator(10)])),
                ('smoking', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
